# Generated by Django 4.0.1 on 2022-01-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='room',
        ),
    ]
