# Generated by Django 4.0.1 on 2022-01-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-updates', '-created']},
        ),
    ]
