# Generated by Django 4.0.1 on 2022-02-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_messages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deprecation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
