# Generated by Django 4.0.1 on 2022-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_deprecation_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(max_length=120),
        ),
    ]
