# Generated by Django 4.0.4 on 2022-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namemove', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
