# Generated by Django 4.0.4 on 2022-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_films'),
    ]

    operations = [
        migrations.CreateModel(
            name='roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftopic', models.CharField(max_length=200)),
                ('namemove', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='تصویر مقاله')),
                ('nameofbtn', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='films',
        ),
    ]
