# Generated by Django 4.0.4 on 2022-05-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_films_remove_roadmaps_namemove_remove_roadmaps_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='url',
            new_name='urlofmove',
        ),
    ]
