# Generated by Django 4.0.4 on 2022-05-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_films_urlofmove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='urlofmove',
            field=models.CharField(max_length=300),
        ),
    ]
